mvcsource/Controllers/VehicleVMController.cs
using assignment_mvc_carrental.Models;
using assignment_mvc_carrental.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;


namespace assignment_mvc_carrental.Controllers
{
    public class VehicleVMController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;
        private readonly IMapper _mapper;

        //För göra risken mindre för strul med deserialisering
        private readonly JsonSerializerOptions _jsonOptions =
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true };

        public VehicleVMController(IMapper mapper, IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
            _mapper = mapper;
        }
//***********************************************************************************************************************
        //Visa ALLA FORDON
        // GET: VehicleVMController/Index
        [Route("allvehicles")]
        public async Task<IActionResult> Index()
        {
            try
            {
                HttpClient client = _clientFactory.CreateClient("CarRentalApi");
                var response = await client.GetAsync("api/VehicleDt");
                if (!response.IsSuccessStatusCode)
                {
                    TempData["ErrorMessage"] = $"Misslyckades hämta fordon från API. Status: {response.StatusCode}";
                    return View("~/Views/VehicleViewModels/Index.cshtml", new List<VehicleViewModel>());
                }

                var stream = await response.Content.ReadAsStreamAsync();
                var vehiclesList = await JsonSerializer.DeserializeAsync<List<Vehicle>>(stream, _jsonOptions)
                                  ?? new List<Vehicle>();

                var vehicleVMList = _mapper.Map<List<VehicleViewModel>>(vehiclesList);
                return View("~/Views/VehicleViewModels/Index.cshtml", vehicleVMList);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occured: ({ex.Message})";
                return View("~/Views/VehicleViewModels/Index.cshtml", new List<VehicleViewModel>());
            }
        }

//***********************************************************************************************************************
        // GET: VehicleVMController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                HttpClient client = _clientFactory.CreateClient("CarRentalApi");

                var response = await client.GetAsync($"api/VehicleDt/{id}");                
                if (!response.IsSuccessStatusCode)
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.NotFound) return NotFound();
                    TempData["ErrorMessage"] = "Could not find vehicle.";
                    return View("Error");
                }

                var vehicleInfo = await response.Content.ReadAsStringAsync();
                var vehicle = JsonSerializer.Deserialize<Vehicle>(vehicleInfo, _jsonOptions);
                if (vehicle == null)
                {
                    return NotFound();
                }

                // 3. Mappa DOMÄNMODEL till VIEWMODEL (Vehicle -> VehicleViewModel)
                var vehicleViewModel = _mapper.Map<VehicleViewModel>(vehicle);

                return View("~/Views/VehicleViewModels/Details.cshtml", vehicleViewModel);
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "An error occured.";
                return View("Error");
            }
        }
//***********************************************************************************************************************
        // GET: VehicleVMController/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View("~/Views/VehicleViewModels/Create.cshtml");
        }

        // POST: VehicleVMController/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Year,PricePerDay,Description,ImageUrl1,ImageUrl2")] VehicleViewModel vehicleViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var vehicle = _mapper.Map<Vehicle>(vehicleViewModel);
                    var vehicleToJson = JsonSerializer.Serialize(vehicle);
                    var vehicleToApi = new StringContent(vehicleToJson, Encoding.UTF8, "application/json");

                    HttpClient client = _clientFactory.CreateClient("CarRentalApi");

                    var response = await client.PostAsync("api/VehicleDt", vehicleToApi);
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["SuccessMessage"] = "Vehicle successfully added!";
                        return RedirectToAction(nameof(Index));
                    }

                    var errorContent = await response.Content.ReadAsStringAsync();
                    ModelState.AddModelError(string.Empty, $"Failed to add vehicle: {response.ReasonPhrase}. Detaljer: {errorContent}");
                }
                catch (Exception)
                {
                    ModelState.AddModelError(string.Empty, "An error occured.");
                }
            }
            return View("~/Views/VehicleViewModels/Create.cshtml", vehicleViewModel);
        }

//***********************************************************************************************************************
        // GET: VehicleVMController/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                HttpClient client = _clientFactory.CreateClient("CarRentalApi");

                var response = await client.GetAsync($"api/VehicleDt/{id.Value}");
                if (!response.IsSuccessStatusCode)
                {
                    return NotFound();
                }

                var vehicleJson = await response.Content.ReadAsStringAsync();
                var vehicle = JsonSerializer.Deserialize<Vehicle>(vehicleJson, _jsonOptions);
                if (vehicle == null)
                {
                    return NotFound();
                }

                var vehicleViewModel = _mapper.Map<VehicleViewModel>(vehicle);
                return View("~/Views/VehicleViewModels/Edit.cshtml", vehicleViewModel);
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "An error occured.";
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: VehicleVMController/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Year,PricePerDay,Description,ImageUrl1,ImageUrl2")] VehicleViewModel vehicleViewModel)
        {
            if (id != vehicleViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var vehicle = _mapper.Map<Vehicle>(vehicleViewModel);
                    var vehicleJson = JsonSerializer.Serialize(vehicle);
                    var vehicleToApi = new StringContent(vehicleJson, Encoding.UTF8, "application/json");

                    HttpClient client = _clientFactory.CreateClient("CarRentalApi");

                    var response = await client.PutAsync($"api/VehicleDt/{id}", vehicleToApi);
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["SuccessMessage"] = "Vehicle was updated!";
                        return RedirectToAction(nameof(Index));
                    }
                    if (response.StatusCode == System.Net.HttpStatusCode.Conflict)
                    {
                        ModelState.AddModelError(string.Empty, "Something went wrong. Please try again.");
                    }
                    else
                    {
                        var errorContent = await response.Content.ReadAsStringAsync();
                        ModelState.AddModelError(string.Empty, $"Unable to update: {response.ReasonPhrase}. Details: {errorContent}");
                    }
                }
                catch (Exception)
                {
                    ModelState.AddModelError(string.Empty, "An error occured.");
                }
            }
            return View("~/Views/VehicleViewModels/Edit.cshtml", vehicleViewModel);
        }


        //***********************************************************************************************************************
        // GET: VehicleVMController/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                HttpClient client = _clientFactory.CreateClient("CarRentalApi");

                var response = await client.GetAsync($"api/VehicleDt/{id.Value}");
                if (!response.IsSuccessStatusCode)
                {
                    return NotFound();
                }

mvcsource/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Friberg Car Rental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/assignment_mvc_carrental.styles.css" asp-append-version="true" />
</head>



<body>
    <header>
        <nav class="navbar navbar-expand-lg mynavbar">
            <div class="container-fluid">
                <img src="~/images/friberglogo.png" class="logo" alt="Friberg Car Rentals Logo" style="max-height: 55px; padding-right: 8px">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Friberg Car Rental</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="VehicleVM" asp-action="Index">See all our vehicles</a>
                        </li>  
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Login">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ApplicationUserVM" asp-action="Register">Register a new account</a>
                        </li>
                    </ul>                    
                </div>
            </div>
        </nav>
    </header>
@*     //Här kan meddelanden/notiser visas för användaren på alla vyer
 *@    <div class="container mt-3">
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                @TempData["SuccessMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                @TempData["ErrorMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }
    </div>
    @*     ********************************************************************************************************** *@

    <div class="container">
        <main role="main" class="pb-3">            
            @RenderBody()
        </main>
    </div>
    <br>
    <br>
    <br>
    <footer class="border-top footer text-muted" style="padding-left: 15px">
        <p>This site is copyrighted by, and trademarked of, Friberg Car Rentals.</p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>